name: dev
on: 
  push: 
    branches:
      - "dev"
  
jobs: 
  delpoy-dev:
    runs-on: ubuntu-latest
    steps:
     - name: Get code
       uses: actions/checkout@v3
     - run: |
        npm install
        npm run build
        
     - name: Upload
       uses: kostya-ten/ssh-server-deploy@v4
       with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        scp_source: "./dist/"
        scp_target: "/root/test/"
        after_script: |
          pm2 restart index
