name: dev
on: 
  push: 
    branches:
      - "dev"
  
jobs: 
  delpoy-dev:
    runs-on: ubuntu-latest
    steps:
     - name: Get code
       uses: actions/checkout@v3
     - run: |
        npm install
        npm run build
        whoami
