name: main
on: push
jobs:
  deplpy-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: |
          npm install
          npm run build
          tar -czvf ${{ github.ref_name }}.tar.gz ./dist

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}

      - name: upload release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ github.ref_name }}.tar.gz
          asset_name: ${{github.ref_name}}.tar.gz
          asset_content_type: application/x-tar

      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: cd /root/test
            wget https://github.com/graywenn/gitdemo/archive/${{github.ref}}.tar.gz -O ${{github.ref_name}}.tar.gz
            tar -xzvf ${{github.ref_name}}.tgz.gz --strip-components 1
